baseurl: 'https://bp.net/' # Website URL

############################
## PERMALINKS
############################

permalinks:
  post: '/post/:slug'
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'

############################
## MODULES
############################

module:
  imports:
    - path: github.com/zeeis/hugo-enterprise

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

# prevent security error
security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
