# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

########################################################################################################################

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Appearance
appearance:
  theme_day: current_theme
  theme_night: current_theme
font_size: L

# Site header
header:
  navbar:
    enable: true
    align: r
    highlight_active_link: true
    show_language: true
    show_translations: true
    show_day_night: true
    show_search: true
    show_logo: true

# Site footer
footer:
  #  text: 'a footer static text'
  copyright:
    notice: 'Copyright ©{year} Alphabiz. All Rights Reserved.'
#  license:
#    enable: true
#    allow_commercial: false
#    allow_derivatives: false
#    share_alike: true

# External js
plugins_js:
  []
plugins_vendor:
  []

# cms config
cms:
  branch: main
  local_backend: false

########################################################################################################################

sharing: false # post share

# contact widget params
#email:
#phone: +86 139-2841-8769‬
#address:
#  street: Room 3003B, Tower A, GALAXY WORLD, No.1 Yabao Road, Bantian Street, Longgang District
#  city: Shenzhen
#  region:
#  postcode:
#  country: China
#directions:
#office_hours:
#appointment_url:
#map:
#  provider: ''
#  api_key: ''
#  zoom: 15

########################################################################################################################

# SEO
site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Site features
highlight: true
highlight_languages:
  - r
math: false
diagram: false
privacy_pack: false
require_isotope: false  # Enable if you use Portfolio widget or Publication pages
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    post: false
show_related:
  post: true
sharing_image: ''
reading_time: true
section_pager: true
#copyright_license:
#  enable: true
#  allow_derivatives: false
#  share_alike: true
#  allow_commercial: false
#  notice: 'This work is licensed under {license}'
avatar:
  gravatar: false
  shape: circle
comments:
  provider: ''
  commentable:
    post: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
icon:
  pack:
    ai: false

