locale:
  date_format: '2006年1月2日'
  time_format: '3:04 PM'
footer:
  copyright:
    notice: '版权所有 ©{year} BP.NET.'
  sharing:
    - type: email
      url: 'example@email'
    - type: github
      url: 'https://github.com/'
    - type: twitter
      url: 'https://twitter.com/'
    - type: linkedin
      url: 'https://www.linkedin.com/'
    - type: facebook
      url: 'https://www.facebook.com/'